<?php
declare(strict_types=1);
require_once __DIR__ . '/../../app/bootstrap.php';

safe_page(function () {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        redirect('/department/create_docs.php');
    }

    require_csrf();
    $user = require_role('department');
    if (!empty($user['mustResetPassword'])) {
        redirect('/auth/force_reset.php');
    }
    $deptId = $user['deptId'] ?? '';
    ensure_department_env($deptId);
    require_department_permission($user, 'generate_docs');

    $templateId = trim((string)($_POST['templateId'] ?? ''));
    $scope = trim((string)($_POST['scope'] ?? ''));
    if ($templateId === '') {
        set_flash('error', 'Template not selected.');
        redirect('/department/create_docs.php');
    }

    $template = create_docs_find_department_template($deptId, $templateId, $scope);
    if (!$template) {
        render_error_page('Template not found or access denied.');
        return;
    }

    $keys = create_docs_collect_template_keys($template);
    $fieldKeys = array_values(array_filter($keys, static fn($key) => !str_starts_with($key, 'table:')));
    $tableKeys = array_values(array_map(static fn($key) => substr($key, 6), array_filter($keys, static fn($key) => str_starts_with($key, 'table:'))));

    $department = load_department($deptId) ?? ['deptId' => $deptId];
    $memory = load_department_memory($deptId);
    $values = create_docs_resolve_department_values($department, $user, department_memory_values($deptId), create_docs_template_title($template));

    $inputFields = $_POST['fields'] ?? [];
    if (!is_array($inputFields)) {
        $inputFields = [];
    }
    foreach ($fieldKeys as $key) {
        if (array_key_exists($key, $inputFields)) {
            $values[$key] = trim((string)$inputFields[$key]);
        }
    }

    $missing = array_values(array_filter($fieldKeys, static function ($key) use ($values) {
        return trim((string)($values[$key] ?? '')) === '';
    }));

    $registry = placeholder_registry([
        'memory' => $memory,
    ]);
    $saveFuture = $_POST['save_future'] ?? [];
    if (is_array($saveFuture)) {
        $entries = [];
        foreach ($saveFuture as $key => $flag) {
            if (!isset($inputFields[$key])) {
                continue;
            }
            $value = trim((string)$inputFields[$key]);
            if ($value === '') {
                continue;
            }
            $meta = $registry['fields'][$key] ?? [];
            $entries[$key] = [
                'value' => $value,
                'label' => $meta['label'] ?? department_memory_label_from_key((string)$key),
                'type' => $meta['type'] ?? 'text',
            ];
        }
        if ($entries) {
            department_memory_upsert_entries($deptId, $entries, 'create_docs');
        }
    }

    $inputTables = $_POST['tables'] ?? [];
    if (!is_array($inputTables)) {
        $inputTables = [];
    }
    $tables = [];
    foreach ($tableKeys as $tableKey) {
        $rows = $inputTables[$tableKey] ?? [];
        if (!is_array($rows)) {
            $rows = [];
        }
        $columns = create_docs_table_columns($tableKey);
        $rows = create_docs_normalize_rows($rows, $columns);
        foreach ($rows as &$row) {
            create_docs_autofill_amount($row);
        }
        unset($row);
        $tables[$tableKey] = $rows;
    }

    [$body, $isHtml] = create_docs_template_body($template);
    $renderMissing = [];
    $renderedBody = create_docs_apply_placeholders($body, $isHtml, $values, $tables, $renderMissing);

    $paper = trim((string)($_POST['paper'] ?? 'A4')) ?: 'A4';
    $letterhead = isset($_POST['letterhead']);
    $headerFooterSpace = isset($_POST['headerFooterSpace']);

    $headerHtml = '';
    $footerHtml = '';
    if ($letterhead) {
        $deptName = $department['nameEn'] ?? ($department['name'] ?? $deptId);
        $deptAddress = $department['address'] ?? '';
        $headerHtml = '<div style="font-weight:700;">' . htmlspecialchars((string)$deptName, ENT_QUOTES, 'UTF-8') . '</div>'
            . ($deptAddress !== '' ? '<div class="muted">' . htmlspecialchars((string)$deptAddress, ENT_QUOTES, 'UTF-8') . '</div>' : '');
    }
    $footerHtml = '<div class="muted">Generated by ' . htmlspecialchars((string)($user['username'] ?? ''), ENT_QUOTES, 'UTF-8')
        . ' on ' . htmlspecialchars(now_kolkata()->format('d M Y H:i'), ENT_QUOTES, 'UTF-8') . '</div>';

    $renderedHtml = create_docs_wrap_html($renderedBody, [
        'paper' => $paper,
        'letterhead' => $letterhead,
        'headerFooterSpace' => $headerFooterSpace,
        'headerHtml' => $headerHtml,
        'footerHtml' => $footerHtml,
        'title' => create_docs_template_title($template),
    ]);

    $docId = create_docs_generate_id(department_generated_docs_path($deptId));
    $now = now_kolkata()->format(DateTime::ATOM);
    $doc = [
        'docId' => $docId,
        'ownerType' => 'department',
        'deptId' => $deptId,
        'templateRef' => [
            'templateId' => create_docs_template_id($template),
            'scope' => $template['scope'] ?? 'department',
        ],
        'title' => create_docs_template_title($template),
        'createdAt' => $now,
        'filled' => [
            'values' => $values,
            'tables' => $tables,
        ],
        'renderedHtml' => $renderedHtml,
        'print' => [
            'paper' => $paper,
            'letterhead' => $letterhead,
            'headerFooterSpace' => $headerFooterSpace,
        ],
        'missingFields' => $renderMissing,
        'audit' => [
            ['at' => $now, 'event' => 'CREATED'],
        ],
    ];

    writeJsonAtomic(department_generated_docs_path($deptId) . '/' . $docId . '.json', $doc);

    logEvent(create_docs_log_path(), [
        'event' => 'doc_generated',
        'ownerType' => 'department',
        'deptId' => $deptId,
        'docId' => $docId,
        'templateId' => create_docs_template_id($template),
        'missingFields' => $missing,
    ]);

    set_flash('success', 'Document generated.');
    redirect('/department/create_doc_view.php?docId=' . urlencode($docId));
});
