<?php
declare(strict_types=1);
require_once __DIR__ . '/../../app/bootstrap.php';

safe_page(function () {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        redirect('/department/quick_doc.php');
    }

    require_csrf();
    $user = require_role('department');
    if (!empty($user['mustResetPassword'])) {
        redirect('/auth/force_reset.php');
    }

    $deptId = $user['deptId'] ?? '';
    ensure_department_env($deptId);
    require_department_permission($user, 'generate_docs');

    $templateId = trim($_POST['templateId'] ?? '');
    $docTitle = trim($_POST['docTitle'] ?? '');
    $tenderId = trim($_POST['tenderId'] ?? '');
    $workorderId = trim($_POST['workorderId'] ?? '');
    $showHeader = isset($_POST['showHeader']);
    $showFooter = isset($_POST['showFooter']);
    $includeLogo = isset($_POST['includeLogo']);

    $templates = array_merge(load_department_templates($deptId), load_global_templates_cache($deptId));
    $template = null;
    foreach ($templates as $tpl) {
        if (($tpl['templateId'] ?? '') === $templateId) {
            $template = $tpl;
            break;
        }
    }

    if (!$template || $docTitle === '') {
        set_flash('error', 'Template or title missing.');
        redirect('/department/quick_doc.php');
    }

    $department = load_department($deptId);
    $replacements = [
        '{{deptName}}' => $department['nameEn'] ?? $deptId,
        '{{tenderId}}' => $tenderId,
        '{{workorderId}}' => $workorderId,
        '{{docDate}}' => now_kolkata()->format('d M Y H:i'),
        '{{userName}}' => $user['displayName'] ?? ($user['username'] ?? ''),
        '{{docTitle}}' => $docTitle,
    ];
    $body = $template['bodyHtml'] ?? '';
    $renderedBody = str_replace(array_keys($replacements), array_values($replacements), $body);

    $header = $showHeader ? '<div style="padding:12px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:12px;">'
        . ($includeLogo ? '<div style="width:48px;height:48px;background:#1f6feb;border-radius:12px;display:grid;place-items:center;font-weight:800;color:#fff;">YJ</div>' : '')
        . '<div><div style="font-weight:700;">' . sanitize($department['nameEn'] ?? 'Department') . '</div>'
        . '<div style="color:var(--muted);font-size:12px;">' . sanitize($deptId) . '</div></div></div>' : '';

    $footer = $showFooter ? '<div style="padding:12px;border-top:1px solid var(--border);margin-top:16px;color:var(--muted);font-size:12px;">'
        . 'Generated by ' . sanitize($user['username'] ?? '') . ' on ' . sanitize(now_kolkata()->format('d M Y H:i')) . '</div>' : '';

    $renderedHtml = '<div style="background:var(--surface);color:var(--text);font-family:Segoe UI,system-ui,sans-serif;">'
        . $header
        . '<div style="padding:16px;">' . $renderedBody . '</div>'
        . $footer
        . '</div>';

    $docId = 'QDOC-' . strtoupper(substr(bin2hex(random_bytes(5)), 0, 10));
    $doc = [
        'docId' => $docId,
        'templateId' => $templateId,
        'docTitle' => $docTitle,
        'inputData' => [
            'tenderId' => $tenderId,
            'workorderId' => $workorderId,
            'options' => [
                'showHeader' => $showHeader,
                'showFooter' => $showFooter,
                'includeLogo' => $includeLogo,
            ],
        ],
        'renderedHtml' => $renderedHtml,
        'createdAt' => now_kolkata()->format(DateTime::ATOM),
        'createdBy' => $user['username'] ?? '',
    ];

    save_generated_doc($deptId, $doc);
    append_department_audit($deptId, [
        'by' => $user['username'] ?? '',
        'action' => 'quick_doc_generated',
        'meta' => ['docId' => $docId, 'templateId' => $templateId],
    ]);

    set_flash('success', 'Document generated.');
    redirect('/department/quick_doc_print.php?docId=' . urlencode($docId));
});
